# Generated by Django 6.0.5 on 2026-06-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('faq_type', models.CharField(choices=[('RIDER', 'Rider'), ('MERCHANT', 'Merchant')], default='RIDER', max_length=20)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(blank=True, help_text='Heading of the slide', max_length=200)),
                ('short_description', models.TextField(blank=True, help_text='Description for the slide')),
                ('image', models.ImageField(help_text='Image for the slide', upload_to='heor_slider_img/')),
                ('cta_message', models.CharField(blank=True, max_length=100)),
                ('primary_btn_txt', models.CharField(blank=True, max_length=100)),
                ('primary_btn_url', models.URLField(blank=True, help_text='URL the button will link to', max_length=250)),
                ('secondary_btn_txt', models.CharField(blank=True, max_length=100)),
                ('secondary_btn_url', models.URLField(blank=True, help_text='URL the button will link to', max_length=250)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadershipMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='leadership/')),
                ('message_01', models.TextField()),
                ('message_02', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('partner_logo', models.ImageField(upload_to='partners/')),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='')),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('mobile_sale', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_support', models.CharField(blank=True, max_length=20, null=True)),
                ('email_sale', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_support', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('office_hours', models.CharField(blank=True, max_length=120, null=True)),
                ('about_company', models.TextField()),
                ('facebook_url', models.URLField(blank=True, default='https://', null=True)),
                ('linkedin_url', models.URLField(blank=True, default='https://', null=True)),
                ('instagram_url', models.URLField(blank=True, default='https://', null=True)),
                ('tiktok_url', models.URLField(blank=True, default='https://', null=True)),
                ('youtube_url', models.URLField(blank=True, default='https://', null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True, help_text='Separate keywords with commas (,).')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('google_site_verification', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.ImageField(upload_to='icons/')),
                ('title', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120, null=True)),
                ('title_ar', models.CharField(max_length=120, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
