# Generated by Django 6.0.5 on 2026-06-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslider',
            name='cta_message_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='cta_message_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='heading_ar',
            field=models.CharField(blank=True, help_text='Heading of the slide', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='heading_en',
            field=models.CharField(blank=True, help_text='Heading of the slide', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='primary_btn_txt_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='primary_btn_txt_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='secondary_btn_txt_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='secondary_btn_txt_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='short_description_ar',
            field=models.TextField(blank=True, help_text='Description for the slide', null=True),
        ),
        migrations.AddField(
            model_name='heroslider',
            name='short_description_en',
            field=models.TextField(blank=True, help_text='Description for the slide', null=True),
        ),
    ]
