# Generated by Django 6.0.5 on 2026-06-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_heroslider_cta_message_ar_heroslider_cta_message_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadershipmessage',
            name='designation_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadershipmessage',
            name='designation_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadershipmessage',
            name='heading_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadershipmessage',
            name='heading_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadershipmessage',
            name='message_01_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='leadershipmessage',
            name='message_01_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='leadershipmessage',
            name='message_02_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadershipmessage',
            name='message_02_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadershipmessage',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadershipmessage',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_company_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_company_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='address_ar',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='address_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mobile_sale_ar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mobile_sale_en',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mobile_support_ar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mobile_support_en',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='office_hours_ar',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='office_hours_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='heading_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='heading_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='image',
            field=models.ImageField(upload_to='heor_slider_img/'),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='primary_btn_url',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='secondary_btn_url',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='short_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='short_description_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
