# Generated by Django 6.0.5 on 2026-06-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(max_length=150)),
                ('heading_en', models.CharField(max_length=150, null=True)),
                ('heading_ar', models.CharField(max_length=150, null=True)),
                ('short_description', models.TextField()),
                ('short_description_en', models.TextField(null=True)),
                ('short_description_ar', models.TextField(null=True)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('mission', models.TextField()),
                ('mission_en', models.TextField(null=True)),
                ('mission_ar', models.TextField(null=True)),
                ('vision', models.TextField()),
                ('vision_en', models.TextField(null=True)),
                ('vision_ar', models.TextField(null=True)),
                ('mission_icon', models.ImageField(blank=True, upload_to='icons/')),
                ('vision_icon', models.ImageField(blank=True, upload_to='icons/')),
                ('feature_01', models.CharField(blank=True, max_length=200)),
                ('feature_01_en', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_01_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_02', models.CharField(blank=True, max_length=200)),
                ('feature_02_en', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_02_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_03', models.CharField(blank=True, max_length=200)),
                ('feature_03_en', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_03_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_04', models.CharField(blank=True, max_length=200)),
                ('feature_04_en', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_04_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_05', models.CharField(blank=True, max_length=200)),
                ('feature_05_en', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_05_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_06', models.CharField(blank=True, max_length=200)),
                ('feature_06_en', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_06_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_07', models.CharField(blank=True, max_length=200)),
                ('feature_07_en', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_07_ar', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpertTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120, null=True)),
                ('name_ar', models.CharField(max_length=120, null=True)),
                ('designation', models.CharField(max_length=120)),
                ('designation_en', models.CharField(max_length=120, null=True)),
                ('designation_ar', models.CharField(max_length=120, null=True)),
                ('photo', models.ImageField(upload_to='expart_teams/')),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ar', models.CharField(max_length=100, null=True)),
                ('short_description', models.TextField(max_length=255)),
                ('short_description_en', models.TextField(max_length=255, null=True)),
                ('short_description_ar', models.TextField(max_length=255, null=True)),
                ('image', models.ImageField(upload_to='working_process/')),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
