# Generated by Django 6.0.5 on 2026-06-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(max_length=150)),
                ('short_description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('mission_icon', models.ImageField(upload_to='icons/')),
                ('vision_icon', models.ImageField(upload_to='icons/')),
                ('feature_01', models.CharField(blank=True, max_length=200)),
                ('feature_02', models.CharField(blank=True, max_length=200)),
                ('feature_03', models.CharField(blank=True, max_length=200)),
                ('feature_04', models.CharField(blank=True, max_length=200)),
                ('feature_05', models.CharField(blank=True, max_length=200)),
                ('feature_06', models.CharField(blank=True, max_length=200)),
                ('feature_07', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='working_process/')),
                ('order', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
