# Generated by Django 6.0.5 on 2026-06-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_about_workingprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='feature_01_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='feature_01_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='feature_02_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='feature_02_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='feature_03_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='feature_03_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='feature_04_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='feature_04_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='feature_05_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='feature_05_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='feature_06_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='feature_06_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='feature_07_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='feature_07_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='heading_ar',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='heading_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='mission_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='mission_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='short_description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='short_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='vision_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='vision_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='expertteam',
            name='designation_ar',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='expertteam',
            name='designation_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='expertteam',
            name='name_ar',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='expertteam',
            name='name_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='workingprocess',
            name='order_ar',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workingprocess',
            name='order_en',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workingprocess',
            name='short_description_ar',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workingprocess',
            name='short_description_en',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workingprocess',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workingprocess',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
