# Generated by Django 6.0.5 on 2026-06-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_about_feature_01_ar_about_feature_01_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingprocess',
            name='order_ar',
        ),
        migrations.RemoveField(
            model_name='workingprocess',
            name='order_en',
        ),
        migrations.AlterField(
            model_name='about',
            name='mission_icon',
            field=models.ImageField(blank=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision_icon',
            field=models.ImageField(blank=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='workingprocess',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
