# Generated by Django 6.0.5 on 2026-06-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='')),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('mobile_sale', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_support', models.CharField(blank=True, max_length=20, null=True)),
                ('email_sale', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_support', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('office_hours', models.CharField(blank=True, max_length=120, null=True)),
                ('facebook_url', models.URLField(blank=True, default='https://', null=True)),
                ('linkedin_url', models.URLField(blank=True, default='https://', null=True)),
                ('instagram_url', models.URLField(blank=True, default='https://', null=True)),
                ('youtube_url', models.URLField(blank=True, default='https://', null=True)),
            ],
        ),
    ]
