# Generated by Django 6.0.5 on 2026-06-16 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='riders/profile/')),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('iqama_number', models.CharField(max_length=50, unique=True)),
                ('iqama_expired_date', models.DateField()),
                ('driving_license_number', models.CharField(max_length=100, unique=True)),
                ('vehicle_type', models.CharField(choices=[('with_car', 'With Car'), ('without_car', 'Without Car')], max_length=30)),
                ('vehicle_plate_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Application'), ('under_review', 'Under Review'), ('interview', 'Interview'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
