# Generated by Django 6.0.5 on 2026-06-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ar', models.CharField(max_length=100, null=True)),
                ('short_description', models.TextField(max_length=100)),
                ('short_description_en', models.TextField(max_length=100, null=True)),
                ('short_description_ar', models.TextField(max_length=100, null=True)),
                ('thumbnail', models.ImageField(upload_to='services/')),
                ('icon', models.ImageField(upload_to='icons/')),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
