# Generated by Django 6.0.7 on 2026-07-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiderRecruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(max_length=200)),
                ('heading_en', models.CharField(max_length=200, null=True)),
                ('heading_ar', models.CharField(max_length=200, null=True)),
                ('short_description', models.TextField()),
                ('short_description_en', models.TextField(null=True)),
                ('short_description_ar', models.TextField(null=True)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('with_car_txt', models.TextField()),
                ('with_car_txt_en', models.TextField(null=True)),
                ('with_car_txt_ar', models.TextField(null=True)),
                ('without_car_txt', models.TextField()),
                ('without_car_txt_en', models.TextField(null=True)),
                ('without_car_txt_ar', models.TextField(null=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
